security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Netgen\LiveVotingBundle\Entity\User: plaintext

    providers:
        entity_provider:
            entity: { class: LiveVotingBundle:User, property: email }
        memory_provider:    
            memory:
                users:
                    admin: { password: morskipas, roles: 'ROLE_ADMIN' }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        admin_secured_area:
            pattern:   ^/admin
            anonymous: ~
            provider: memory_provider
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin
            logout:

        user_secured_area:
            pattern:   ^/
            anonymous: ~
            provider: entity_provider
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /home

        default:
            anonymous: ~
  