security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Netgen\LiveVotingBundle\Entity\User: plaintext

    providers:
        db_provider:
            entity: { class: LiveVotingBundle:User }
        memory_provider:
            memory:
                users:
                    admin: { password: %admin_password%, roles: 'ROLE_ADMIN' }
    role_hierarchy:
        ROLE_ADMIN:    ROLE_USER

    access_control:
        admin_login:
            path: /admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        admin_area:
            path: /admin/.*
            roles: ROLE_ADMIN
        members_area:
            path: /user/.*
            roles: ROLE_USER
        event_area:
            path: /event/.*
            roles: ROLE_ADMIN


    firewalls:
        admin:
          pattern: ^/admin.*
          anonymous: ~
          context: livevoting
          form_login:
            login_path: /admin/login
            check_path: /admin/login_check
            default_target_path: /admin
          logout:
            path: /admin/logout
          provider: memory_provider

        user:
          pattern: ^/.*
          anonymous: ~
          context: livevoting
          form_login:
            login_path: /login
            check_path: /login_check
            default_target_path: /user
            remember_me: true
          remember_me:
            key: "%secret%"
            lifetime: 15768000 # 6 months in seconds
            path: /
          logout:
            path: /logout
          provider: db_provider
