security:
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: morskipas, roles: 'ROLE_ADMIN' }
                    other: { password: abc, roles: 'ROLE_USER'}

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: "LiveVoting admin panel"
            form_login:
                login_path: login
                check_path: login_check
    

        default:
            anonymous: ~
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
